### ISSUE TITLE
Running sample script gives error

### ISSUE THREAD

**Issue by robotpukeko** [ayakashi-io/ayakashi#9]
Hi,

I'm running beta v1.6 on nodejs v10.15.3 on Ubuntu 18.04.2 LTS and get the following error when running the sample script from the documentation : 
`[01:45:30] Ayakashi version: 1.0.0-beta1.6
[01:45:30] running scrapper in simple mode
[01:45:30] directory: /home/steve/ayakashi
[01:45:30] scrapper: github.js
[01:45:30] data will be printed to console, specify --out=sqlite|json|csv to change the format
[01:45:30] downloading latest chromium for Linux_x64
◤ 112.599MB/115.703MB(node:20229) UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed
    at arrayBufferConstructor_DoNotInitialize (<anonymous>)
    at new Uint8Array (<anonymous>)
    at module.exports.input (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress-tar/node_modules/file-type/index.js:4:14)
    at input (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress-tar/index.js:11:34)
    at Promise.all.opts.plugins.map.x (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress/index.js:19:43)
    at Array.map (<anonymous>)
    at runPlugins (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress/index.js:19:34)
    at extractFile (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress/index.js:22:46)
    at read.then.buf (/home/steve/.nvm/versions/node/v10.15.3/lib/node_modules/ayakashi/node_modules/decompress/index.js:95:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I'm using node under nvm, so I'm not sure if that would cause the issue.

Cheers
Steve

**Comment by zisismaras** [comment]
Hey there,

It seems the system couldn't allocate enough memory to download and extract chromium.
Is your system low on memory or maybe out of memory at the time?

I'll see how to make the download more efficient by flushing to disk while downloading/extracting and not keeping the whole thing in memory.

In the meantime you could download chromium manually from [here](https://download-chromium.appspot.com/) and extract it in a `.chromium` directory next to your script.

Just let me know if you are still having issues

**Comment by robotpukeko** [comment]
Hi,

Yes, it was the memory, as I was using the smallest shared instance VM Google offer and it ran out. I did up it to 1.7Gb, with the download of Chromium completing, but the decompression of the package also hung for a long time, with the activity spinner stopping completely.

I downloaded the standalone Linux x64 version and unzipped to a .chromium directory, with the following result : 

```
steve@pg-controller:~/ayakashi$ ayakashi run --simple ./github.js
[07:35:45] Ayakashi version: 1.0.0-beta1.6
[07:35:45] running scrapper in simple mode
[07:35:45] directory: /home/steve/ayakashi
[07:35:45] scrapper: github.js
[07:35:45] data will be printed to console, specify --out=sqlite|json|csv to change the format
[07:35:59] Failed to run project
[07:35:59] Something went wrong Error: Can't launch Chrome! (attempts: 2/3)
```
This was unzipping all the Chromium files to the .chromium directory directly. I then unzipped using the default folder structure as part of the zip and got this error : 

```
[07:38:28] Ayakashi version: 1.0.0-beta1.6
[07:38:28] running scrapper in simple mode
[07:38:28] directory: /home/steve/ayakashi
[07:38:28] scrapper: github.js
[07:38:28] data will be printed to console, specify --out=sqlite|json|csv to change the format
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/steve/ayakashi/.chromium/chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I downloaded the version of Chromium from this link : https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots

Thanks

**Comment by zisismaras** [comment]
Hey,

It seems chromium is missing some dependencies if the environment has no graphical interface.
You could try installing a system-level chromium from your package manager
```bash
sudo apt-get install chromium-browser
```
This will also install all the missing dependencies and the local chromium will work.

Or you could install just the missing dependencies as described here:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

Both ways should work.

Make sure the folder structure is like your first example (unzipping the files in the `.chromium` directory)

If you'd like you could also update to the latest version which improves memory usage:
```bash
npm update -g ayakashi
```

Most of the time i use a vps with 1.5-2g ram so chromium has enough memory to run comfortably.

Let me know if you are still facing issues,
Thanks

**Comment by zisismaras** [comment]
Instructions on how to install missing dependencies on a linux server have been added here: https://ayakashi.io/docs/installation
